#!/usr/bin/env python3
"""
Script generated by AI to check my bounding boxes for any points that are outside the normalized [0.0, 1.0] range. 
"""

import os
import sys

# Configurations
WORKSPACE_DIR = os.path.dirname(os.path.abspath(__file__))
MVP_DIR = os.path.join(WORKSPACE_DIR, "datasets", "mvp_2")
LABELS_DIR = os.path.join(MVP_DIR, "labels")

def scan_labels():
    print("==================================================")
    print("YOLO OBB Label Boundary Scanner")
    print("==================================================")
    
    if not os.path.exists(LABELS_DIR):
        print(f"[!] Error: Labels directory not found at {LABELS_DIR}")
        print("    Please run 'prepare_dataset.py' first.")
        sys.exit(1)
        
    splits = ["train", "val"]
    
    # Global counters
    total_files_scanned = 0
    total_boxes_scanned = 0
    total_offending_files = 0
    total_offending_boxes = 0
    
    # Stats trackers
    global_min_coord = 0.0
    global_min_file = ""
    global_max_coord = 1.0
    global_max_file = ""
    
    # Detailed list of offending coordinates
    offending_records = []
    
    for split in splits:
        split_dir = os.path.join(LABELS_DIR, split)
        if not os.path.exists(split_dir):
            continue
            
        files = [f for f in os.listdir(split_dir) if f.lower().endswith('.txt')]
        print(f"[*] Scanning split '{split}': Found {len(files)} label files...")
        
        for file in files:
            path = os.path.join(split_dir, file)
            total_files_scanned += 1
            
            # Read label file
            try:
                with open(path, "r", encoding="utf-8") as f:
                    lines = f.readlines()
            except Exception as e:
                print(f"    [!] Error reading {file}: {e}")
                continue
                
            file_has_offending_box = False
            
            for line_idx, line in enumerate(lines):
                line = line.strip()
                if not line:
                    continue
                    
                tokens = line.split()
                # standard OBB has 9 tokens: class_idx + 8 coordinates
                if len(tokens) < 9:
                    continue
                    
                total_boxes_scanned += 1
                
                class_idx = tokens[0]
                try:
                    coords = [float(c) for c in tokens[1:9]]
                except ValueError:
                    print(f"    [!] Warning: Non-float coordinates in {file} at line {line_idx+1}")
                    continue
                    
                # Scan coordinates
                box_offending = False
                offending_coords_in_box = []
                
                for c_idx, c in enumerate(coords):
                    # Keep track of absolute min/max values
                    if c < global_min_coord:
                        global_min_coord = c
                        global_min_file = f"{split}/{file}"
                    if c > global_max_coord:
                        global_max_coord = c
                        global_max_file = f"{split}/{file}"
                        
                    # Check boundary
                    if c < 0.0 or c > 1.0:
                        box_offending = True
                        offending_coords_in_box.append((c_idx, c))
                        
                if box_offending:
                    file_has_offending_box = True
                    total_offending_boxes += 1
                    offending_records.append({
                        "split": split,
                        "filename": file,
                        "line_num": line_idx + 1,
                        "class_idx": class_idx,
                        "tokens": tokens,
                        "offending_coords": offending_coords_in_box
                    })
                    
            if file_has_offending_box:
                total_offending_files += 1
                
    # Compile and print Report
    print("\n==================================================")
    print("Label Boundary Statistics Report")
    print("==================================================")
    print(f"[*] Files Scanned: {total_files_scanned}")
    print(f"[*] Bounding Boxes Scanned: {total_boxes_scanned}")
    print(f"[*] Files with Out-of-Bounds Boxes: {total_offending_files}")
    print(f"[*] Total Out-of-Bounds Boxes: {total_offending_boxes}")
    print("--------------------------------------------------")
    
    # Absolute extremities
    print(f"[*] Extremity Metrics:")
    if global_min_file:
        print(f"    - Minimum Coordinate Found: {global_min_coord:.6f} (in {global_min_file})")
    else:
        print(f"    - Minimum Coordinate Found: 0.000000 (Perfect left/top bound)")
        
    if global_max_file:
        print(f"    - Maximum Coordinate Found: {global_max_coord:.6f} (in {global_max_file})")
    else:
        print(f"    - Maximum Coordinate Found: 1.000000 (Perfect right/bottom bound)")
    print("--------------------------------------------------")
    
    # Detailed list of out-of-bounds coordinates
    if offending_records:
        print("[!] Detailed Bounding Box Breach Log:")
        for idx, rec in enumerate(offending_records):
            print(f"    [{idx+1}] File: {rec['split']}/{rec['filename']} | Line: {rec['line_num']} | Class: {rec['class_idx']}")
            # Show breach coordinates
            breach_strs = []
            for c_idx, val in rec['offending_coords']:
                coord_name = f"x{c_idx//2 + 1}" if c_idx % 2 == 0 else f"y{c_idx//2 + 1}"
                breach_strs.append(f"{coord_name}={val:.6f}")
            print(f"        Breaches: {', '.join(breach_strs)}")
            print(f"        Raw line: {rec['tokens'][0]} " + " ".join([f"{float(x):.6f}" for x in rec['tokens'][1:9]]))
    else:
        print("[+] SUCCESS: Zero out-of-bounds bounding boxes found. Every coordinate is safely within the [0.0, 1.0] image frame!")
        
    print("==================================================")

if __name__ == "__main__":
    scan_labels()
